# JPA ??
spring:
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/elasticsearchtest
    username: root
    password: 1234
